---
- include_vars: default-config.yml
# install the varinsh modules and apache modules
- name: Install the Apache Server
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ system_modules }}"
  become: true
  become_user: root
